//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolovCircus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int IDPicture { get; set; }
        public string Picture1 { get; set; }
        public int IDShow { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
